<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Buku;
use Carbon\Carbon;

class BukuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $buku = [
            // Penulis: Tere Liye (ID: 1)
            [
                'judul' => 'Hujan',
                'penulis_id' => 1,
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => 2016,
                'kategori_id' => 1,
                'stok' => 5,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Tentang Kamu',
                'penulis_id' => 1,
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => 2015,
                'kategori_id' => 1,
                'stok' => 3,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Bumi (Seri Bumi #1)',
                'penulis_id' => 1,
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => 2014,
                'kategori_id' => 1,
                'stok' => 4,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Bulan (Seri Bumi #2)',
                'penulis_id' => 1,
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => 2015,
                'kategori_id' => 1,
                'stok' => 4,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // Penulis: Andrea Hirata (ID: 2)
            [
                'judul' => 'Laskar Pelangi',
                'penulis_id' => 2,
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => 2005,
                'kategori_id' => 1,
                'stok' => 7,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Sang Pemimpi',
                'penulis_id' => 2,
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => 2006,
                'kategori_id' => 1,
                'stok' => 4,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Edensor',
                'penulis_id' => 2,
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => 2007,
                'kategori_id' => 1,
                'stok' => 3,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Maryamah Karpov',
                'penulis_id' => 2,
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => 2008,
                'kategori_id' => 1,
                'stok' => 2,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // Penulis: Pramoedya Ananta Toer (ID: 3)
            [
                'judul' => 'Bumi Manusia',
                'penulis_id' => 3,
                'penerbit' => 'Hasta Mitra',
                'tahun_terbit' => 1980,
                'kategori_id' => 1,
                'stok' => 2,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Anak Semua Bangsa',
                'penulis_id' => 3,
                'penerbit' => 'Hasta Mitra',
                'tahun_terbit' => 1981,
                'kategori_id' => 1,
                'stok' => 2,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Jejak Langkah',
                'penulis_id' => 3,
                'penerbit' => 'Hasta Mitra',
                'tahun_terbit' => 1985,
                'kategori_id' => 1,
                'stok' => 1,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // Penulis: Raditya Dika (ID: 4)
            [
                'judul' => 'Kambing Jantan',
                'penulis_id' => 4,
                'penerbit' => 'Gagas Media',
                'tahun_terbit' => 2005,
                'kategori_id' => 1,
                'stok' => 6,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Cinta Brontosaurus',
                'penulis_id' => 4,
                'penerbit' => 'Gagas Media',
                'tahun_terbit' => 2006,
                'kategori_id' => 1,
                'stok' => 5,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Radikus Makankakus',
                'penulis_id' => 4,
                'penerbit' => 'Gagas Media',
                'tahun_terbit' => 2007,
                'kategori_id' => 1,
                'stok' => 4,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // Penulis: Dewi Lestari (ID: 5)
            [
                'judul' => 'Filosofi Kopi',
                'penulis_id' => 5,
                'penerbit' => 'Truedee Books',
                'tahun_terbit' => 2006,
                'kategori_id' => 1,
                'stok' => 5,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Supernova: Kesatria, Putri, & Bintang Jatuh',
                'penulis_id' => 5,
                'penerbit' => 'Truedee Books',
                'tahun_terbit' => 2001,
                'kategori_id' => 1,
                'stok' => 3,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Supernova: Akar',
                'penulis_id' => 5,
                'penerbit' => 'Truedee Books',
                'tahun_terbit' => 2003,
                'kategori_id' => 1,
                'stok' => 3,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // Penulis: Habiburrahman El Shirazy (ID: 6)
            [
                'judul' => 'Ayat-Ayat Cinta',
                'penulis_id' => 6,
                'penerbit' => 'Republika',
                'tahun_terbit' => 2004,
                'kategori_id' => 5,
                'stok' => 8,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Ketika Cinta Bertasbih',
                'penulis_id' => 6,
                'penerbit' => 'Republika',
                'tahun_terbit' => 2005,
                'kategori_id' => 5,
                'stok' => 4,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Bulan Terbelah di Langit Amerika',
                'penulis_id' => 6,
                'penerbit' => 'Republika',
                'tahun_terbit' => 2010,
                'kategori_id' => 5,
                'stok' => 3,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // Buku Teknologi & Pendidikan
            [
                'judul' => 'Pemrograman Web dengan Laravel 10',
                'penulis_id' => 4,
                'penerbit' => 'Elex Media Komputindo',
                'tahun_terbit' => 2023,
                'kategori_id' => 4,
                'stok' => 10,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Database MySQL untuk Pemula',
                'penulis_id' => 4,
                'penerbit' => 'Informatika',
                'tahun_terbit' => 2022,
                'kategori_id' => 4,
                'stok' => 8,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Artificial Intelligence: Konsep dan Implementasi',
                'penulis_id' => 5,
                'penerbit' => 'Andi Offset',
                'tahun_terbit' => 2023,
                'kategori_id' => 4,
                'stok' => 5,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Machine Learning dengan Python',
                'penulis_id' => 5,
                'penerbit' => 'Andi Offset',
                'tahun_terbit' => 2022,
                'kategori_id' => 4,
                'stok' => 5,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Sejarah Indonesia Modern',
                'penulis_id' => 2,
                'penerbit' => 'Erlangga',
                'tahun_terbit' => 2019,
                'kategori_id' => 2,
                'stok' => 3,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Matematika Dasar untuk Perguruan Tinggi',
                'penulis_id' => 1,
                'penerbit' => 'Yrama Widya',
                'tahun_terbit' => 2020,
                'kategori_id' => 3,
                'stok' => 6,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Fisika Modern: Teori dan Aplikasi',
                'penulis_id' => 3,
                'penerbit' => 'Graha Ilmu',
                'tahun_terbit' => 2021,
                'kategori_id' => 3,
                'stok' => 4,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Kimia Organik: Prinsip Dasar',
                'penulis_id' => 3,
                'penerbit' => 'Erlangga',
                'tahun_terbit' => 2020,
                'kategori_id' => 3,
                'stok' => 4,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Biologi Sel dan Molekuler',
                'penulis_id' => 2,
                'penerbit' => 'Gadjah Mada University Press',
                'tahun_terbit' => 2021,
                'kategori_id' => 3,
                'stok' => 3,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Psikologi Pendidikan',
                'penulis_id' => 5,
                'penerbit' => 'Rajawali Pers',
                'tahun_terbit' => 2019,
                'kategori_id' => 3,
                'stok' => 5,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Manajemen Bisnis Modern',
                'penulis_id' => 1,
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => 2021,
                'kategori_id' => 7,
                'stok' => 7,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Kesehatan Mental di Era Digital',
                'penulis_id' => 5,
                'penerbit' => 'Bentang Pustaka',
                'tahun_terbit' => 2022,
                'kategori_id' => 8,
                'stok' => 6,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Seni Lukis Tradisional Indonesia',
                'penulis_id' => 2,
                'penerbit' => 'Balai Pustaka',
                'tahun_terbit' => 2018,
                'kategori_id' => 9,
                'stok' => 4,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Jaringan Komputer: Teori dan Praktik',
                'penulis_id' => 4,
                'penerbit' => 'Informatika',
                'tahun_terbit' => 2022,
                'kategori_id' => 10,
                'stok' => 8,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Steve Jobs: Biografi Pendiri Apple',
                'penulis_id' => 3,
                'penerbit' => 'Gramedia Pustaka Utama',
                'tahun_terbit' => 2011,
                'kategori_id' => 6,
                'stok' => 3,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'judul' => 'Nelson Mandela: Long Walk to Freedom',
                'penulis_id' => 3,
                'penerbit' => 'Mizan',
                'tahun_terbit' => 2010,
                'kategori_id' => 6,
                'stok' => 2,
                'cover_buku' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($buku as $data) {
            Buku::create($data);
        }
    }
}